site_name: Build a full Rails stack with Docker and AWS Copilot
repo_url: https://github.com/build-with-aws-copilot/rails
repo_name: build-with-aws-copilot/rails
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - announce.dismiss

nav:
  - Overview: index.md
  - 'Getting Started': getting_started.md
  - 'Creating Dockerfile': creating_dockerfile.md
  - 'Provisioning Infrastructure on AWS': provisioning_infrastructure.md
  - 'Deploying Webserver to AWS': 'deploying_webserver_to_aws.md'
  - 'Rails Console': 'rails_console.md'
  - 'CI/CD on GitHub Actions': 'ci_cd.md'
  - 'Adding Redis': 'adding_redis.md'
  - 'Deploying Worker to AWS': 'deploying_worker_to_aws.md'
  - 'Passing build time variables to Dockerfile': 'passing_build_time_variables_to_dockerfile.md'
  - 'ECS Graceful Shutdown': 'ecs_graceful_shutdown.md'
  - 'Adding Postgres': 'adding_postgres.md'
  - 'Database Migration': 'database_migration.md'
  - 'Adding SSL/TLS Certificate': 'adding_ssl_tls_certificate.md'
  - 'Adding Your Domain': 'adding_your_domain.md'
  - 'Complete Stack': 'complete_stack.md'
  - 'About the Author': 'about_the_author.md'
extra:
  analytics:
    provider: google
    property: G-3V5Y9CDCVG
    
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
