site_name: Build a full web stack with Docker and AWS Copilot (Rails Edition)
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking

nav:
  - Overview: index.md
  - 'Getting Started': getting_started.md
  - 'Creating Dockerfile': creating_dockerfile.md
  - 'Provisioning Infrastructure on AWS': provisioning_infrastructure.md
  - 'Deploying Webserver to AWS': 'deploying_webserver_to_aws.md'
  - 'Rails Console': 'rails_console.md'
  - 'CI/CD on GitHub Actions': 'ci_cd.md'
  - 'Adding Redis': 'adding_redis.md'
  - 'Deploying Worker to AWS': 'deploying_worker_to_aws.md'
  - 'Overriding Copilot Defaults': 'overriding_copilot_defaults.md'
  - 'Adding Postgres': 'adding_postgres.md'
  - 'Database Migration': 'database_migration.md'
  - 'Adding SSL/TLS Certificate': 'adding_ssl_tls_certificate.md'
  - 'Adding Your Domain': 'adding_your_domain.md'
  - 'Complete Stack': 'complete_stack.md'
extra:
  analytics:
    provider: google
    property: G-3V5Y9CDCVG
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/richardchou89/
    
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html