site_name: Build a full web stack with Docker and AWS Copilot (Rails Edition)
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking

nav:
  - Overview: index.md
  - 'Getting Started': getting_started.md
  - 'Creating Dockerfile': creating_dockerfile.md
  - 'Provisioning Infrastructure on AWS': provisioning_infrastructure.md
  - 'Deploying Webserver to AWS': 'deploying_webserver_to_aws.md'
extra:
  analytics:
    provider: google
    property: G-3V5Y9CDCVG
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/richardchou89/
    
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html